/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vista;
import controlador.ControladorCartelera;
import java.awt.Component;
import java.awt.event.ActionListener;
import java.awt.event.MouseListener;
import modelo.entidad.Pelicula;
import java.util.List;
import javax.swing.JButton;
import javax.swing.JLabel;

/**
 *
 * @author Matth
 */
public class VistaCartelera extends javax.swing.JPanel {
    private List<Pelicula> peliculasCargadas;
    private ControladorCartelera controladorCartelera;

    public VistaCartelera() {
        initComponents();
        jScrollPane1.getVerticalScrollBar().setUnitIncrement(30);
        controladorCartelera = new ControladorCartelera();
        cargarCartelera();
    }
   private void cargarCartelera() {
   // se cargan las peliculas con el controaldor
        this.peliculasCargadas = controladorCartelera.obtenerListaPeliculas();  
        List<Pelicula> lista = this.peliculasCargadas;
        
        JButton[] botones = {
            btnPelicula1, btnPelicula2, btnPelicula3, btnPelicula4, 
            btnPelicula5, btnPelicula6, btnPelicula7, btnPelicula8, 
            btnPelicula9, btnPelicula10, btnPelicula11, btnPelicula12
        };
        
        JLabel[] posters = {
            poster1, poster2, poster3, poster4, 
            poster5, poster6, poster7, poster8, 
            poster9, poster10, poster11, poster12
        };

        //se pide al controlador que cargue todo
        controladorCartelera.cargarDatosEnVista(lista, botones, posters);
        
        //se modifica los botones
        for (int i = 0; i < botones.length; i++) {
            final int index = i;
            
            botones[i].setBorderPainted(false);
            botones[i].setContentAreaFilled(false);
            botones[i].setFocusPainted(false);
            
            for (ActionListener al : botones[i].getActionListeners()) {
                botones[i].removeActionListener(al);
            }
            
            botones[i].addActionListener(e -> {
                if (index < lista.size()) {
                    abrirDetalles(index);
                }
            });
            
            for (MouseListener ml : posters[i].getMouseListeners()) {
                posters[i].removeMouseListener(ml);
            }
            
            posters[i].addMouseListener(new java.awt.event.MouseAdapter() {
                @Override
                public void mouseClicked(java.awt.event.MouseEvent evt) {
                    if (index < lista.size()) {
                        abrirDetalles(index);
                    }
                }
            });
        }
}
    private void abrirDetalles(int indice) {
        if (peliculasCargadas != null && indice < peliculasCargadas.size()) {
            Pelicula p = peliculasCargadas.get(indice);
            
            vista.VistaPrincipal principal = (vista.VistaPrincipal) javax.swing.SwingUtilities.getWindowAncestor(this);
            
            for (Component comp : principal.contenedorPrincipal.getComponents()) {
                if (comp instanceof vista.VistaDetalles individual) {
                    individual.cargarDatosDetalle(p);
                    principal.cambiarPantalla("pantallaDetalle"); 
                }
            }
        }
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        contenedorPosters = new javax.swing.JPanel();
        poster1 = new javax.swing.JLabel();
        btnPelicula1 = new javax.swing.JButton();
        poster2 = new javax.swing.JLabel();
        btnPelicula2 = new javax.swing.JButton();
        poster3 = new javax.swing.JLabel();
        btnPelicula3 = new javax.swing.JButton();
        poster4 = new javax.swing.JLabel();
        btnPelicula4 = new javax.swing.JButton();
        poster5 = new javax.swing.JLabel();
        btnPelicula5 = new javax.swing.JButton();
        poster6 = new javax.swing.JLabel();
        btnPelicula6 = new javax.swing.JButton();
        poster7 = new javax.swing.JLabel();
        btnPelicula7 = new javax.swing.JButton();
        poster8 = new javax.swing.JLabel();
        btnPelicula8 = new javax.swing.JButton();
        poster9 = new javax.swing.JLabel();
        btnPelicula9 = new javax.swing.JButton();
        poster10 = new javax.swing.JLabel();
        btnPelicula10 = new javax.swing.JButton();
        poster11 = new javax.swing.JLabel();
        btnPelicula11 = new javax.swing.JButton();
        poster12 = new javax.swing.JLabel();
        btnPelicula12 = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(1256, 591));

        jScrollPane1.setBorder(null);
        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);
        jScrollPane1.setPreferredSize(new java.awt.Dimension(1100, 500));

        contenedorPosters.setBackground(new java.awt.Color(153, 153, 153));
        contenedorPosters.setPreferredSize(new java.awt.Dimension(1100, 1250));

        poster1.setBackground(new java.awt.Color(255, 255, 255));
        poster1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        poster1.setOpaque(true);
        poster1.setPreferredSize(new java.awt.Dimension(200, 300));
        poster1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                poster1MouseClicked(evt);
            }
        });

        btnPelicula1.setFont(new java.awt.Font("Sitka Text", 1, 18)); // NOI18N
        btnPelicula1.setText("NOMBREE");
        btnPelicula1.setBorder(null);
        btnPelicula1.setBorderPainted(false);
        btnPelicula1.setFocusPainted(false);

        poster2.setBackground(new java.awt.Color(255, 255, 255));
        poster2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        poster2.setOpaque(true);
        poster2.setPreferredSize(new java.awt.Dimension(200, 300));
        poster2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                poster2MouseClicked(evt);
            }
        });

        btnPelicula2.setFont(new java.awt.Font("Sitka Text", 1, 18)); // NOI18N
        btnPelicula2.setText("NOMBREE");
        btnPelicula2.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnPelicula2.setBorderPainted(false);
        btnPelicula2.setFocusPainted(false);

        poster3.setBackground(new java.awt.Color(255, 255, 255));
        poster3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        poster3.setOpaque(true);
        poster3.setPreferredSize(new java.awt.Dimension(200, 300));
        poster3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                poster3MouseClicked(evt);
            }
        });

        btnPelicula3.setFont(new java.awt.Font("Sitka Text", 1, 18)); // NOI18N
        btnPelicula3.setText("NOMBREE");
        btnPelicula3.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnPelicula3.setBorderPainted(false);
        btnPelicula3.setFocusPainted(false);

        poster4.setBackground(new java.awt.Color(255, 255, 255));
        poster4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        poster4.setOpaque(true);
        poster4.setPreferredSize(new java.awt.Dimension(200, 300));
        poster4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                poster4MouseClicked(evt);
            }
        });

        btnPelicula4.setFont(new java.awt.Font("Sitka Text", 1, 18)); // NOI18N
        btnPelicula4.setText("NOMBREE");
        btnPelicula4.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnPelicula4.setBorderPainted(false);
        btnPelicula4.setFocusPainted(false);

        poster5.setBackground(new java.awt.Color(255, 255, 255));
        poster5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        poster5.setOpaque(true);
        poster5.setPreferredSize(new java.awt.Dimension(200, 300));
        poster5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                poster5MouseClicked(evt);
            }
        });

        btnPelicula5.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnPelicula5.setText("NOMBREE");
        btnPelicula5.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnPelicula5.setBorderPainted(false);
        btnPelicula5.setFocusPainted(false);
        btnPelicula5.addActionListener(this::btnPelicula5ActionPerformed);

        poster6.setBackground(new java.awt.Color(255, 255, 255));
        poster6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        poster6.setOpaque(true);
        poster6.setPreferredSize(new java.awt.Dimension(200, 300));
        poster6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                poster6MouseClicked(evt);
            }
        });

        btnPelicula6.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnPelicula6.setText("NOMBREE");
        btnPelicula6.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnPelicula6.setBorderPainted(false);
        btnPelicula6.setFocusPainted(false);

        poster7.setBackground(new java.awt.Color(255, 255, 255));
        poster7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        poster7.setOpaque(true);
        poster7.setPreferredSize(new java.awt.Dimension(200, 300));
        poster7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                poster7MouseClicked(evt);
            }
        });

        btnPelicula7.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnPelicula7.setText("NOMBREE");
        btnPelicula7.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnPelicula7.setBorderPainted(false);
        btnPelicula7.setFocusPainted(false);

        poster8.setBackground(new java.awt.Color(255, 255, 255));
        poster8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        poster8.setOpaque(true);
        poster8.setPreferredSize(new java.awt.Dimension(200, 300));
        poster8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                poster8MouseClicked(evt);
            }
        });

        btnPelicula8.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnPelicula8.setText("NOMBREE");
        btnPelicula8.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnPelicula8.setBorderPainted(false);
        btnPelicula8.setFocusPainted(false);

        poster9.setBackground(new java.awt.Color(255, 255, 255));
        poster9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        poster9.setOpaque(true);
        poster9.setPreferredSize(new java.awt.Dimension(200, 300));
        poster9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                poster9MouseClicked(evt);
            }
        });

        btnPelicula9.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnPelicula9.setText("NOMBREE");
        btnPelicula9.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnPelicula9.setBorderPainted(false);
        btnPelicula9.setFocusPainted(false);

        poster10.setBackground(new java.awt.Color(255, 255, 255));
        poster10.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        poster10.setOpaque(true);
        poster10.setPreferredSize(new java.awt.Dimension(200, 300));
        poster10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                poster10MouseClicked(evt);
            }
        });

        btnPelicula10.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnPelicula10.setText("NOMBREE");
        btnPelicula10.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnPelicula10.setBorderPainted(false);
        btnPelicula10.setFocusPainted(false);

        poster11.setBackground(new java.awt.Color(255, 255, 255));
        poster11.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        poster11.setOpaque(true);
        poster11.setPreferredSize(new java.awt.Dimension(200, 300));
        poster11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                poster11MouseClicked(evt);
            }
        });

        btnPelicula11.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnPelicula11.setText("NOMBREE");
        btnPelicula11.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnPelicula11.setBorderPainted(false);
        btnPelicula11.setFocusPainted(false);

        poster12.setBackground(new java.awt.Color(255, 255, 255));
        poster12.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        poster12.setOpaque(true);
        poster12.setPreferredSize(new java.awt.Dimension(200, 300));
        poster12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                poster12MouseClicked(evt);
            }
        });

        btnPelicula12.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnPelicula12.setText("NOMBREE");
        btnPelicula12.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnPelicula12.setBorderPainted(false);
        btnPelicula12.setFocusPainted(false);

        javax.swing.GroupLayout contenedorPostersLayout = new javax.swing.GroupLayout(contenedorPosters);
        contenedorPosters.setLayout(contenedorPostersLayout);
        contenedorPostersLayout.setHorizontalGroup(
            contenedorPostersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contenedorPostersLayout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addComponent(poster1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(poster2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(poster3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(poster4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(contenedorPostersLayout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addComponent(btnPelicula1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(70, 70, 70)
                .addComponent(btnPelicula2, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(70, 70, 70)
                .addComponent(btnPelicula3, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(70, 70, 70)
                .addComponent(btnPelicula4, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(contenedorPostersLayout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addComponent(poster5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(poster6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(poster7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(poster8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(contenedorPostersLayout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addComponent(btnPelicula5, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(70, 70, 70)
                .addComponent(btnPelicula6, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(70, 70, 70)
                .addComponent(btnPelicula7, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(70, 70, 70)
                .addComponent(btnPelicula8, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(contenedorPostersLayout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addComponent(poster9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(poster10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(poster11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(poster12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(contenedorPostersLayout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addComponent(btnPelicula9, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(70, 70, 70)
                .addComponent(btnPelicula10, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(70, 70, 70)
                .addComponent(btnPelicula11, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(70, 70, 70)
                .addComponent(btnPelicula12, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        contenedorPostersLayout.setVerticalGroup(
            contenedorPostersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contenedorPostersLayout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(contenedorPostersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(poster1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(poster2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(poster3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(poster4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(contenedorPostersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnPelicula1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPelicula2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPelicula3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPelicula4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addGroup(contenedorPostersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(poster5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(poster6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(poster7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(poster8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(contenedorPostersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnPelicula5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPelicula6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPelicula7, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPelicula8, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addGroup(contenedorPostersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(poster9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(poster10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(poster11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(poster12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(contenedorPostersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnPelicula9, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPelicula10, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPelicula11, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPelicula12, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        jScrollPane1.setViewportView(contenedorPosters);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(88, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 520, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(46, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    
    private void poster1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_poster1MouseClicked
    abrirDetalles(0);
     
    }//GEN-LAST:event_poster1MouseClicked

    private void poster2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_poster2MouseClicked
      abrirDetalles(1);
    }//GEN-LAST:event_poster2MouseClicked

    private void poster3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_poster3MouseClicked
        abrirDetalles(2);
    }//GEN-LAST:event_poster3MouseClicked

    private void poster4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_poster4MouseClicked
        abrirDetalles(3);
    }//GEN-LAST:event_poster4MouseClicked

    private void poster5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_poster5MouseClicked
       abrirDetalles(4);
    }//GEN-LAST:event_poster5MouseClicked

    private void poster6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_poster6MouseClicked
        abrirDetalles(5);
    }//GEN-LAST:event_poster6MouseClicked

    private void poster7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_poster7MouseClicked
      abrirDetalles(6);
    }//GEN-LAST:event_poster7MouseClicked

    private void poster8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_poster8MouseClicked
       abrirDetalles(7);
    }//GEN-LAST:event_poster8MouseClicked

    private void poster9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_poster9MouseClicked
     abrirDetalles(8);
    }//GEN-LAST:event_poster9MouseClicked

    private void poster12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_poster12MouseClicked
        abrirDetalles(11);
    }//GEN-LAST:event_poster12MouseClicked

    private void poster10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_poster10MouseClicked
       abrirDetalles(9);
    }//GEN-LAST:event_poster10MouseClicked

    private void poster11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_poster11MouseClicked
        abrirDetalles(10);
    }//GEN-LAST:event_poster11MouseClicked

    private void btnPelicula5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPelicula5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPelicula5ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnPelicula1;
    public javax.swing.JButton btnPelicula10;
    public javax.swing.JButton btnPelicula11;
    public javax.swing.JButton btnPelicula12;
    public javax.swing.JButton btnPelicula2;
    public javax.swing.JButton btnPelicula3;
    public javax.swing.JButton btnPelicula4;
    public javax.swing.JButton btnPelicula5;
    public javax.swing.JButton btnPelicula6;
    public javax.swing.JButton btnPelicula7;
    public javax.swing.JButton btnPelicula8;
    public javax.swing.JButton btnPelicula9;
    public javax.swing.JPanel contenedorPosters;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JLabel poster1;
    public javax.swing.JLabel poster10;
    public javax.swing.JLabel poster11;
    public javax.swing.JLabel poster12;
    public javax.swing.JLabel poster2;
    public javax.swing.JLabel poster3;
    public javax.swing.JLabel poster4;
    public javax.swing.JLabel poster5;
    public javax.swing.JLabel poster6;
    public javax.swing.JLabel poster7;
    public javax.swing.JLabel poster8;
    public javax.swing.JLabel poster9;
    // End of variables declaration//GEN-END:variables
}
