package vista;
import controlador.ControladorNavegacion;
import java.awt.CardLayout;
import java.awt.EventQueue;
import java.awt.Image;
import java.awt.event.ActionListener;
import javax.swing.ImageIcon;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import javax.swing.JPasswordField;
import javax.swing.Timer;
import javax.swing.UnsupportedLookAndFeelException;
public class VistaPrincipal extends javax.swing.JFrame {
   private ControladorNavegacion controladorNavegacion;
    /**
     * Creates new form PaginaPrincipal
     */
    public VistaPrincipal() {
        initComponents();
        controladorNavegacion = new ControladorNavegacion();
        btnRegresar.setVisible(false);
        btnCartelera.setVisible(false);
        cargarLogo();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelBase = new javax.swing.JPanel();
        btnRegresar = new javax.swing.JButton();
        contenedorPrincipal = new javax.swing.JPanel();
        vistaCartelera1 = new vista.VistaCartelera();
        vistaDetalles1 = new vista.VistaDetalles();
        vistaSeleccionAsientos1 = new vista.VistaSeleccionAsientos();
        vistaPago1 = new vista.VistaPago();
        btnCartelera = new javax.swing.JButton();
        btnIngresar = new javax.swing.JButton();
        lblLogo = new javax.swing.JLabel();
        Separador = new javax.swing.JSeparator();
        lbliconoadm = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        PanelBase.setBackground(new java.awt.Color(17, 17, 17));
        PanelBase.setPreferredSize(new java.awt.Dimension(1280, 719));

        btnRegresar.setBackground(new java.awt.Color(174, 149, 90));
        btnRegresar.setFont(new java.awt.Font("HP Simplified Hans Light", 1, 18)); // NOI18N
        btnRegresar.setText("←");
        btnRegresar.setBorderPainted(false);
        btnRegresar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRegresar.setFocusPainted(false);
        btnRegresar.addActionListener(this::btnRegresarActionPerformed);

        contenedorPrincipal.setBackground(new java.awt.Color(204, 204, 204));
        contenedorPrincipal.setForeground(new java.awt.Color(255, 255, 255));
        contenedorPrincipal.setPreferredSize(new java.awt.Dimension(1256, 635));
        contenedorPrincipal.setLayout(new java.awt.CardLayout());

        vistaCartelera1.setBackground(new java.awt.Color(17, 17, 17));
        contenedorPrincipal.add(vistaCartelera1, "pantallaCartelera");
        contenedorPrincipal.add(vistaDetalles1, "pantallaDetalle");
        contenedorPrincipal.add(vistaSeleccionAsientos1, "pantallaAsientos");
        contenedorPrincipal.add(vistaPago1, "pantallaPago");

        btnCartelera.setBackground(new java.awt.Color(174, 149, 90));
        btnCartelera.setFont(new java.awt.Font("Nirmala UI Semilight", 1, 18)); // NOI18N
        btnCartelera.setText("Cartelera");
        btnCartelera.setBorderPainted(false);
        btnCartelera.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCartelera.setFocusPainted(false);
        btnCartelera.addActionListener(this::btnCarteleraActionPerformed);

        btnIngresar.setBackground(new java.awt.Color(174, 149, 90));
        btnIngresar.setFont(new java.awt.Font("Nirmala UI Semilight", 1, 18)); // NOI18N
        btnIngresar.setText("ADMINISTRADOR");
        btnIngresar.setToolTipText("");
        btnIngresar.setBorderPainted(false);
        btnIngresar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnIngresar.setFocusPainted(false);
        btnIngresar.addActionListener(this::btnIngresarActionPerformed);

        lblLogo.setForeground(new java.awt.Color(17, 17, 17));

        Separador.setBackground(new java.awt.Color(174, 149, 90));
        Separador.setForeground(new java.awt.Color(174, 149, 90));

        lbliconoadm.setBackground(new java.awt.Color(17, 17, 17));
        lbliconoadm.setForeground(new java.awt.Color(174, 149, 90));
        lbliconoadm.setText("👤");
        lbliconoadm.setOpaque(true);

        javax.swing.GroupLayout PanelBaseLayout = new javax.swing.GroupLayout(PanelBase);
        PanelBase.setLayout(PanelBaseLayout);
        PanelBaseLayout.setHorizontalGroup(
            PanelBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelBaseLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(lblLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnRegresar, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnCartelera)
                .addGap(18, 18, 18)
                .addComponent(lbliconoadm, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnIngresar)
                .addGap(29, 29, 29))
            .addGroup(PanelBaseLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(contenedorPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, 1290, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(Separador)
        );
        PanelBaseLayout.setVerticalGroup(
            PanelBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelBaseLayout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addGroup(PanelBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(PanelBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnRegresar, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnCartelera, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnIngresar, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lbliconoadm))
                    .addComponent(lblLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(Separador, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(contenedorPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 614, Short.MAX_VALUE)
                .addGap(15, 15, 15))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PanelBase, javax.swing.GroupLayout.DEFAULT_SIZE, 1302, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PanelBase, javax.swing.GroupLayout.DEFAULT_SIZE, 743, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void cargarLogo(){
        ImageIcon icon = new ImageIcon("Imagenes/Logo.png");
        Image img = icon.getImage().getScaledInstance(
            lblLogo.getWidth(),
            lblLogo.getHeight(),
            Image.SCALE_SMOOTH);
            lblLogo.setIcon(new ImageIcon(img));
    }
    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        //encargamos la navegacion al controlador
        String siguientePantalla = controladorNavegacion.procesarRetroceso(contenedorPrincipal);
        
        CardLayout cl = (CardLayout) contenedorPrincipal.getLayout();
        cl.show(contenedorPrincipal, siguientePantalla);

        // Si se regresa a la cartelera se limpian los datos
        if ("pantallaCartelera".equals(siguientePantalla)) {
            limpiarPantallaDetalle();
        }
        //control de visibilidad d botones
        btnRegresar.setVisible(controladorNavegacion.debeMostrarBotonRegresar(siguientePantalla));
        btnCartelera.setVisible(!"pantallaCartelera".equals(siguientePantalla));
    }//GEN-LAST:event_btnRegresarActionPerformed

    private void btnCarteleraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCarteleraActionPerformed
        cambiarPantalla("pantallaCartelera");
    }//GEN-LAST:event_btnCarteleraActionPerformed

    private void btnIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresarActionPerformed
    //se crea el cuadro para la contraseña
    JPasswordField pwdField = new JPasswordField();
    
    //se crea el cuadro
    Object[] mensaje = {
        "Por favor, ingresa la contraseña de administrador:", 
        pwdField
    };
    
    //se muestra el cuadro
    int opcion = javax.swing.JOptionPane.showConfirmDialog(
        this, 
        mensaje, 
        "Acceso de Administrador", 
        JOptionPane.OK_CANCEL_OPTION, 
        JOptionPane.PLAIN_MESSAGE
    );
    
    //si se presiona ok
    if (opcion == javax.swing.JOptionPane.OK_OPTION) {
        String passwordIngresada = new String(pwdField.getPassword());
        
        //se verifica si la contraseña es correcta
        if (passwordIngresada.equals(VistaAdministrador.getPasswordAdmin())) {
            
            //se crea el cuadro de dialogo
            JOptionPane optionPane = new JOptionPane(
                "¡Bienvenido, Administrador!", 
                JOptionPane.INFORMATION_MESSAGE
            );
            
            JDialog dialog = optionPane.createDialog(this, "Acceso Exitoso");
            
            // Temporizador para cerrarlo solo el tiempo esta en microsegundos
            Timer timer = new javax.swing.Timer(700, new ActionListener() {
                @Override
                public void actionPerformed(java.awt.event.ActionEvent e) {
                    dialog.dispose();
                }
            });
            timer.setRepeats(false);
            timer.start();
            
            dialog.setVisible(true);
            
            // se abre la ventana del admin
            VistaAdministrador ventanaAdmin = new VistaAdministrador();
            ventanaAdmin.setLocationRelativeTo(null);
            ventanaAdmin.setVisible(true);
            
            // se cierra la ventana actual
            this.dispose();
            
        } else {
            //si la contraseña es incorrecta
            JOptionPane.showMessageDialog(
                this, 
                "Contraseña incorrecta.", 
                "Error de Acceso", 
                JOptionPane.ERROR_MESSAGE
            );
        }
    }
    }//GEN-LAST:event_btnIngresarActionPerformed

    public void cambiarPantalla(String nombreCard) {
            CardLayout cl = (CardLayout) contenedorPrincipal.getLayout();
        cl.show(contenedorPrincipal, nombreCard);

        //si se regresa a la cartelera se limpian los datos de las pantallas
        if ("pantallaCartelera".equals(nombreCard)) {
            limpiarPantallaDetalle();
        }

        btnRegresar.setVisible(controladorNavegacion.debeMostrarBotonRegresar(nombreCard));
        btnCartelera.setVisible(!"pantallaCartelera".equals(nombreCard));

    }
    public void limpiarPantallaDetalle() {
        vistaDetalles1.limpiarFormularioPelicula();
        vistaSeleccionAsientos1.reiniciarColoresYEstadosBotones();
}

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | IllegalAccessException | InstantiationException | UnsupportedLookAndFeelException ex) {
        }

        /* Create and display the form */
        EventQueue.invokeLater(() -> {
            new VistaPrincipal().setVisible(true);});
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelBase;
    private javax.swing.JSeparator Separador;
    public javax.swing.JButton btnCartelera;
    public javax.swing.JButton btnIngresar;
    public javax.swing.JButton btnRegresar;
    public javax.swing.JPanel contenedorPrincipal;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JLabel lbliconoadm;
    private vista.VistaCartelera vistaCartelera1;
    private vista.VistaDetalles vistaDetalles1;
    private vista.VistaPago vistaPago1;
    private vista.VistaSeleccionAsientos vistaSeleccionAsientos1;
    // End of variables declaration//GEN-END:variables
}
