/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import controlador.ControladorAdministrador;
import controlador.GestorCine;
import java.awt.Image;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JPasswordField;
import javax.swing.JScrollPane;
import javax.swing.JTextArea;
import javax.swing.JTextField;
import modelo.entidad.Funcion;
import modelo.entidad.Pelicula;
/**
 *
 * @author Matth
 */
public class VistaAdministrador extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VistaAdministrador.class.getName());
    private javax.swing.table.DefaultTableModel modeloTabla;
    private ControladorAdministrador controlador = new ControladorAdministrador();
    private static String passwordAdmin = "admin";
    /**
     * Creates new form VistaAdministrador
     */
    public VistaAdministrador() {
        initComponents();
        jScrollPane1.getVerticalScrollBar().setUnitIncrement(30);
        configurarTablaAdmin(); 
        cargarPeliculasEnTabla(controlador.obtenerListaPeliculas());
        cargarLogoAdmin();
    }
     private void cargarLogoAdmin(){
        ImageIcon icon = new ImageIcon("Imagenes/Logo.png");
        Image img = icon.getImage().getScaledInstance(
            lblLogoAdmin.getWidth(),
            lblLogoAdmin.getHeight(),
            Image.SCALE_SMOOTH);
            lblLogoAdmin.setIcon(new ImageIcon(img));
    }
    
    public static void setPasswordAdmin(String nuevaPass) {
        passwordAdmin = nuevaPass;
    }

    public static String getPasswordAdmin() {
        return passwordAdmin;
    }
    
    private void configurarTablaAdmin() {
    String[] columnas = {"ID", "Título", "Género", "Clasificación", "Precio ($)"};
        
        modeloTabla = new javax.swing.table.DefaultTableModel(columnas, 0) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        tablaPeliculas.setModel(modeloTabla);
}

    private void cargarPeliculasEnTabla(java.util.List<Pelicula> listaPeliculas) {
        modeloTabla.setRowCount(0); 

        for (Pelicula p : listaPeliculas) {
            Object[] fila = {
                p.getId(),
                p.getTitulo(),
                p.getGenero(),
                p.getClasificacion(),
                String.format("%.2f", p.getPrecio())
            };
            modeloTabla.addRow(fila);
        }
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaPeliculas = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        btnEliminar = new javax.swing.JButton();
        btnAñadir = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        btnConfigurarContraseña = new javax.swing.JButton();
        btnVerVentas = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        cmbSeccionAdmin = new javax.swing.JComboBox<>();
        lblbo = new javax.swing.JLabel();
        lblvi = new javax.swing.JLabel();
        lblmo = new javax.swing.JLabel();
        lblañ = new javax.swing.JLabel();
        lblcon = new javax.swing.JLabel();
        lblLogoAdmin = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(17, 17, 17));
        jPanel1.setPreferredSize(new java.awt.Dimension(1280, 719));

        jScrollPane1.setBackground(new java.awt.Color(235, 235, 235));

        tablaPeliculas.setFont(new java.awt.Font("Segoe UI Variable", 0, 14)); // NOI18N
        tablaPeliculas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "TITULO", "GENERO", "CALSIFICACION", "PRECIO"
            }
        ));
        jScrollPane1.setViewportView(tablaPeliculas);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(240, 240, 240));
        jLabel1.setText("PANEL ADMINISTRADOR");

        btnEliminar.setBackground(new java.awt.Color(201, 176, 102));
        btnEliminar.setFont(new java.awt.Font("Nirmala UI Semilight", 1, 14)); // NOI18N
        btnEliminar.setText("ELIMINAR");
        btnEliminar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEliminar.addActionListener(this::btnEliminarActionPerformed);

        btnAñadir.setBackground(new java.awt.Color(201, 176, 102));
        btnAñadir.setFont(new java.awt.Font("Nirmala UI Semilight", 1, 14)); // NOI18N
        btnAñadir.setText("AÑADIR");
        btnAñadir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAñadir.addActionListener(this::btnAñadirActionPerformed);

        btnModificar.setBackground(new java.awt.Color(201, 176, 102));
        btnModificar.setFont(new java.awt.Font("Nirmala UI Semilight", 1, 14)); // NOI18N
        btnModificar.setText("MODIFICAR");
        btnModificar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnModificar.addActionListener(this::btnModificarActionPerformed);

        btnSalir.setBackground(new java.awt.Color(174, 149, 90));
        btnSalir.setFont(new java.awt.Font("Leelawadee UI", 1, 14)); // NOI18N
        btnSalir.setText(" Salir");
        btnSalir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSalir.addActionListener(this::btnSalirActionPerformed);

        btnConfigurarContraseña.setBackground(new java.awt.Color(201, 176, 102));
        btnConfigurarContraseña.setFont(new java.awt.Font("Nirmala UI Semilight", 1, 14)); // NOI18N
        btnConfigurarContraseña.setText("Configurar Contraseña");
        btnConfigurarContraseña.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnConfigurarContraseña.addActionListener(this::btnConfigurarContraseñaActionPerformed);

        btnVerVentas.setBackground(new java.awt.Color(201, 176, 102));
        btnVerVentas.setFont(new java.awt.Font("Nirmala UI Semilight", 1, 14)); // NOI18N
        btnVerVentas.setText("VER VENTAS");
        btnVerVentas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnVerVentas.addActionListener(this::btnVerVentasActionPerformed);

        jLabel2.setFont(new java.awt.Font("Nirmala UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(240, 240, 240));
        jLabel2.setText("Mostrar:");

        cmbSeccionAdmin.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Peliculas", "Funciones", "Salas" }));
        cmbSeccionAdmin.addActionListener(this::cmbSeccionAdminActionPerformed);

        lblbo.setBackground(new java.awt.Color(201, 176, 102));
        lblbo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblbo.setText("🗑");
        lblbo.setOpaque(true);

        lblvi.setBackground(new java.awt.Color(201, 176, 102));
        lblvi.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblvi.setText("👁");
        lblvi.setOpaque(true);

        lblmo.setBackground(new java.awt.Color(201, 176, 102));
        lblmo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblmo.setText("🖉");
        lblmo.setOpaque(true);

        lblañ.setBackground(new java.awt.Color(201, 176, 102));
        lblañ.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblañ.setText("+");
        lblañ.setOpaque(true);

        lblcon.setBackground(new java.awt.Color(201, 176, 102));
        lblcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblcon.setText("⛭");
        lblcon.setOpaque(true);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(280, 280, 280)
                        .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 821, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblañ, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnAñadir, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(54, 54, 54)
                                .addComponent(lblbo, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(52, 52, 52)
                                .addComponent(lblvi, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnVerVentas, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(55, 55, 55)
                                .addComponent(lblmo, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(26, 26, 26)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnConfigurarContraseña, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblcon, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lblLogoAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)))
                .addGap(42, 42, 42))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmbSeccionAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbSeccionAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(63, 63, 63)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnAñadir, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblañ, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblbo, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnVerVentas, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblvi, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblmo, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(46, 46, 46)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(117, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
                        .addComponent(lblLogoAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnConfigurarContraseña, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblcon, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(174, 174, 174))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 12, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 23, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 696, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
    int filaSeleccionada = tablaPeliculas.getSelectedRow();
    
    if (filaSeleccionada == -1) {
        JOptionPane.showMessageDialog(this, "Por favor, selecciona un elemento de la tabla para eliminar.", "Aviso", JOptionPane.WARNING_MESSAGE);
        return;
    }
    
    String seccionActual = cmbSeccionAdmin.getSelectedItem().toString();
    int idSeleccionado = Integer.parseInt(tablaPeliculas.getValueAt(filaSeleccionada, 0).toString());
    
    int confirmacion = JOptionPane.showConfirmDialog(
        this, "¿Estás seguro de que deseas eliminar este elemento?", "Confirmar Eliminación", JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE
    );
    
    if (confirmacion == JOptionPane.YES_OPTION) {
        boolean eliminado = controlador.eliminarElementoPorSeccion(seccionActual, idSeleccionado);
        
        if (eliminado) {
            controlador.cambiarVistaTabla(seccionActual, tablaPeliculas);
            JOptionPane.showMessageDialog(this, "Elemento eliminado con éxito.");
            
        } else {
            JOptionPane.showMessageDialog(this, "No se pudo eliminar el elemento del archivo.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnConfigurarContraseñaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfigurarContraseñaActionPerformed
        //se crea un panel para pedir la nueva
    JPanel panelDialogo = new JPanel(new java.awt.GridLayout(2, 1, 5, 5));
    JLabel etiqueta = new JLabel("Configura una nueva contraseña de administrador:");
    JPasswordField campoPassword = new JPasswordField();
    
    panelDialogo.add(etiqueta);
    panelDialogo.add(campoPassword);
    
    //se pide confirmacion para cambiar contraseña
    int resultado = JOptionPane.showConfirmDialog(
        this, 
        panelDialogo, 
        "Configurar Contraseña", 
        JOptionPane.OK_CANCEL_OPTION, 
        JOptionPane.PLAIN_MESSAGE
    );
    
    // si selecciono ok
    if (resultado == JOptionPane.OK_OPTION) {
        String nuevaPass = new String(campoPassword.getPassword()).trim();
        
        if (nuevaPass.isEmpty()) {
            JOptionPane.showMessageDialog(
                this, 
                "La contraseña no puede estar vacía.", 
                "Error", 
                JOptionPane.ERROR_MESSAGE
            );
            return;
        }
        
        //se guarda la contraseña que se ingreso
        VistaAdministrador.setPasswordAdmin(nuevaPass);
        
        JOptionPane.showMessageDialog(
            this, 
            "¡Contraseña configurada con éxito! Usela la próxima vez que ingrese.", 
            "Guardado", 
            JOptionPane.INFORMATION_MESSAGE
        );
    }
    }//GEN-LAST:event_btnConfigurarContraseñaActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        VistaPrincipal ventanaPrincipal = new VistaPrincipal();
        ventanaPrincipal.setLocationRelativeTo(null);
        ventanaPrincipal.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnAñadirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAñadirActionPerformed
        String seccionActual = cmbSeccionAdmin.getSelectedItem().toString();

    switch (seccionActual) {
        case "Peliculas": {
            JTextField txtId = new JTextField();
            JTextField txtTitulo = new JTextField();
            JTextField txtSinopsis = new JTextField();
            JTextField txtGenero = new JTextField();
            JTextField txtDuracion = new JTextField();
            JTextField txtClasificacion = new JTextField();
            JTextField txtRutaImagen = new JTextField();
            JTextField txtPrecio = new JTextField();
            
            Object[] formulario = {
                "ID:", txtId, "Título:", txtTitulo, "Sinopsis:", txtSinopsis,
                "Género:", txtGenero, "Duración (min):", txtDuracion,
                "Clasificación:", txtClasificacion, "Nombre Imagen:", txtRutaImagen,
                "Precio ($):", txtPrecio
            };
            
            int opcion = JOptionPane.showConfirmDialog(this, formulario, "Registrar Película", JOptionPane.OK_CANCEL_OPTION, JOptionPane.PLAIN_MESSAGE);
            if (opcion == JOptionPane.OK_OPTION) {
                try {
                    int id = Integer.parseInt(txtId.getText().trim());
                    if (controlador.buscarPeliculaPorId(id) != null) {
                        JOptionPane.showMessageDialog(this, "El ID ya existe.", "Error", JOptionPane.ERROR_MESSAGE);
                        return;
                    }
                    boolean guardado = controlador.crearPelicula(
                        id, txtTitulo.getText().trim(), txtSinopsis.getText().trim(),
                        txtGenero.getText().trim(), Integer.parseInt(txtDuracion.getText().trim()),
                        txtClasificacion.getText().trim(), txtRutaImagen.getText().trim(),
                        Double.parseDouble(txtPrecio.getText().trim())
                    );
                    if (guardado) {
                        controlador.cambiarVistaTabla("Peliculas", tablaPeliculas);
                        JOptionPane.showMessageDialog(this, "¡Película agregada con éxito!");
                    }
                } catch (NumberFormatException e) {
                    JOptionPane.showMessageDialog(this, "Verifica los campos numéricos.", "Error", JOptionPane.ERROR_MESSAGE);
                }
            }
            break;
        }
        case "Salas": {
            JTextField txtIdSala = new JTextField();
            JTextField txtNombre = new JTextField();
            JTextField txtCapacidad = new JTextField();
            Object[] formulario = {"ID Sala:", txtIdSala, "Nombre Sala:", txtNombre, "Capacidad:", txtCapacidad};
            
            int opcion = JOptionPane.showConfirmDialog(this, formulario, "Registrar Sala", JOptionPane.OK_CANCEL_OPTION, JOptionPane.PLAIN_MESSAGE);
            if (opcion == JOptionPane.OK_OPTION) {
                try {
                    boolean guardado = controlador.crearSala(
                        Integer.parseInt(txtIdSala.getText().trim()), 
                        txtNombre.getText().trim(), 
                        Integer.parseInt(txtCapacidad.getText().trim())
                    );
                    if (guardado) {
                        controlador.cambiarVistaTabla("Salas", tablaPeliculas);
                        JOptionPane.showMessageDialog(this, "¡Sala agregada con éxito!");
                    } else {
                        JOptionPane.showMessageDialog(this, "No se pudo guardar la sala.", "Error", JOptionPane.ERROR_MESSAGE);
                    }
                } catch (NumberFormatException e) {
                    JOptionPane.showMessageDialog(this, "Verifica que el ID y la capacidad sean numéricos.", "Error", JOptionPane.ERROR_MESSAGE);
                }
            }
            break;
        }
        case "Funciones": {
            JTextField txtIdFun = new JTextField();
            JTextField txtIdPel = new JTextField();
            JTextField txtIdSal = new JTextField();
            JTextField txtHorario = new JTextField();
            Object[] formulario = {"ID Función:", txtIdFun, "ID Película:", txtIdPel, "ID Sala:", txtIdSal, "Horario (ej. 14:00):", txtHorario};
            
            int opcion = JOptionPane.showConfirmDialog(this, formulario, "Registrar Función", JOptionPane.OK_CANCEL_OPTION, JOptionPane.PLAIN_MESSAGE);
            if (opcion == JOptionPane.OK_OPTION) {
                try {
                    boolean guardado = controlador.crearFuncion(
                        Integer.parseInt(txtIdFun.getText().trim()), 
                        Integer.parseInt(txtIdPel.getText().trim()), 
                        Integer.parseInt(txtIdSal.getText().trim()), 
                        txtHorario.getText().trim()
                    );
                    if (guardado) {
                        controlador.cambiarVistaTabla("Funciones", tablaPeliculas);
                        JOptionPane.showMessageDialog(this, "¡Función agregada con éxito!");
                    } else {
                        JOptionPane.showMessageDialog(this, "No se pudo guardar la función. Verifica que los IDs de Película y Sala existan.", "Error", JOptionPane.ERROR_MESSAGE);
                    }
                } catch (NumberFormatException e) {
                    JOptionPane.showMessageDialog(this, "Verifica que los IDs sean numéricos.", "Error", JOptionPane.ERROR_MESSAGE);
                }
            }
            break;
        }
    }
    }//GEN-LAST:event_btnAñadirActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
            int filaSeleccionada = tablaPeliculas.getSelectedRow();
    if (filaSeleccionada == -1) {
        JOptionPane.showMessageDialog(this, "Por favor, selecciona un elemento de la tabla para modificar.", "Aviso", JOptionPane.WARNING_MESSAGE);
        return;
    }
    
    int idSeleccionado = Integer.parseInt(tablaPeliculas.getValueAt(filaSeleccionada, 0).toString());
    String seccionActual = cmbSeccionAdmin.getSelectedItem().toString();

    switch (seccionActual) {
        case "Peliculas": {
            Pelicula p = controlador.buscarPeliculaPorId(idSeleccionado);
            if (p == null) return;
            
            JTextField txtTitulo = new JTextField(p.getTitulo());
            JTextField txtSinopsis = new JTextField(p.getSipnopsis());
            JTextField txtGenero = new JTextField(p.getGenero());
            JTextField txtDuracion = new JTextField(String.valueOf(p.getDuracion()));
            JTextField txtClasificacion = new JTextField(p.getClasificacion());
            JTextField txtRutaImagen = new JTextField(controlador.limpiarRutaImagen(p.getRutaImagen()));
            JTextField txtPrecio = new JTextField(String.valueOf(p.getPrecio()));
            
            Object[] formulario = {
                "Título:", txtTitulo, "Sinopsis:", txtSinopsis, "Género:", txtGenero,
                "Duración (min):", txtDuracion, "Clasificación:", txtClasificacion,
                "Nombre Imagen:", txtRutaImagen, "Precio ($):", txtPrecio
            };
            
            if (JOptionPane.showConfirmDialog(this, formulario, "Modificar Película", JOptionPane.OK_CANCEL_OPTION, JOptionPane.PLAIN_MESSAGE) == JOptionPane.OK_OPTION) {
                try {
                    boolean actualizado = controlador.actualizarPelicula(
                        idSeleccionado, txtTitulo.getText().trim(), txtSinopsis.getText().trim(),
                        txtGenero.getText().trim(), Integer.parseInt(txtDuracion.getText().trim()),
                        txtClasificacion.getText().trim(), txtRutaImagen.getText().trim(),
                        Double.parseDouble(txtPrecio.getText().trim())
                    );
                    if (actualizado) {
                        controlador.cambiarVistaTabla("Peliculas", tablaPeliculas);
                        JOptionPane.showMessageDialog(this, "¡Película modificada con éxito!");
                    }
                } catch (NumberFormatException e) {
                    JOptionPane.showMessageDialog(this, "Verifica que los campos numéricos sean correctos.", "Error", JOptionPane.ERROR_MESSAGE);
                }
            }
            break;
        }
        case "Salas": {
            String nombreActual = tablaPeliculas.getValueAt(filaSeleccionada, 1).toString();
            String capacidadActual = tablaPeliculas.getValueAt(filaSeleccionada, 2).toString();

            JTextField txtNombre = new JTextField(nombreActual);
            JTextField txtCapacidad = new JTextField(capacidadActual);
            
            Object[] formulario = {"Nombre Sala:", txtNombre, "Capacidad:", txtCapacidad};
            if (JOptionPane.showConfirmDialog(this, formulario, "Modificar Sala", JOptionPane.OK_CANCEL_OPTION, JOptionPane.PLAIN_MESSAGE) == JOptionPane.OK_OPTION) {
                try {
                    controlador.editarSala(idSeleccionado, txtNombre.getText().trim(), Integer.parseInt(txtCapacidad.getText().trim()));
                    controlador.cambiarVistaTabla("Salas", tablaPeliculas);
                    JOptionPane.showMessageDialog(this, "¡Sala modificada con éxito!");
                } catch (NumberFormatException e) {
                    JOptionPane.showMessageDialog(this, "Verifica que la capacidad sea un número válido.", "Error", JOptionPane.ERROR_MESSAGE);
                }
            }
            break;
        }
        case "Funciones": {
            //se coge el id 
            int idFuncion = Integer.parseInt(tablaPeliculas.getValueAt(filaSeleccionada, 0).toString());

            //buscamos la funcion con el id
            Funcion funcionActual = null;
            for (Funcion f : controlador.obtenerListaFunciones()) {
                if (f.getIdFuncion() == idFuncion) {
                    funcionActual = f;
                    break;
                }
            }

            if (funcionActual == null) {
                JOptionPane.showMessageDialog(this, "No se encontró la función seleccionada.", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }

            //se cargan los datos
            JTextField txtIdPeli = new JTextField(String.valueOf(funcionActual.getPelicula().getId()));
            JTextField txtIdSala = new JTextField(String.valueOf(funcionActual.getSala().getIdSala()));
            JTextField txtHorario = new JTextField(funcionActual.getHorario());
            
            Object[] formulario = {"ID Película:", txtIdPeli, "ID Sala:", txtIdSala, "Horario:", txtHorario};
            
            if (JOptionPane.showConfirmDialog(this, formulario, "Modificar Función", JOptionPane.OK_CANCEL_OPTION, JOptionPane.PLAIN_MESSAGE) == JOptionPane.OK_OPTION) {
                try {
                    controlador.editarFuncion(
                        idFuncion, 
                        Integer.parseInt(txtIdPeli.getText().trim()), 
                        Integer.parseInt(txtIdSala.getText().trim()), 
                        txtHorario.getText().trim()
                    );
                    controlador.cambiarVistaTabla("Funciones", tablaPeliculas);
                    JOptionPane.showMessageDialog(this, "¡Función modificada con éxito!");
                } catch (NumberFormatException e) {
                    JOptionPane.showMessageDialog(this, "Verifica que los IDs sean numéricos.", "Error", JOptionPane.ERROR_MESSAGE);
                }
            }
            break;
        }
    }
    }//GEN-LAST:event_btnModificarActionPerformed

    private void btnVerVentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerVentasActionPerformed
                //instanciar boletosdao
            modelo.dao.BoletoDAO daoBoletos = new modelo.dao.BoletoDAO();
            List<modelo.entidad.Boleto> listaBoletos = daoBoletos.obtenerBoletos();

            //s no hay ventas registradas se muestra mensaje de que esta vacio
            if (listaBoletos == null || listaBoletos.isEmpty()) {
                JOptionPane.showMessageDialog(
                    this, 
                    "No hay boletos vendidos registrados todavía.", 
                    "Reporte de Ventas", 
                    JOptionPane.INFORMATION_MESSAGE
                );
                return;
            }

            //se muestra un cuador de dialogo para mostrar todas las entradas
            StringBuilder resumen = new StringBuilder("---ENTRADAS VENDIDAS---\n\n");
            for (modelo.entidad.Boleto b : listaBoletos) {
                resumen.append("Película: ").append(b.getPelicula())
                       .append(" | Asientos: ").append(b.getAsientos())
                       .append(" | Total: $").append(b.getTotal())
                       .append("\n----------------------------------------------------------------------------------------------\n");
            }

            //se muestra el cuadro de dialogo
            JTextArea textArea = new JTextArea(resumen.toString(), 15, 40);
            textArea.setEditable(false);
            JScrollPane scrollPane = new JScrollPane(textArea);

            JOptionPane.showMessageDialog(
                this, 
                scrollPane, 
                "Boletos vendidos", 
                javax.swing.JOptionPane.PLAIN_MESSAGE
            );
    }//GEN-LAST:event_btnVerVentasActionPerformed

    private void cmbSeccionAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbSeccionAdminActionPerformed
        // Obtenemos la opción seleccionada ("Películas", "Salas" o "Funciones")
    String opcionSeleccionada = cmbSeccionAdmin.getSelectedItem().toString();
    
    // Llamamos al controlador usando tu variable 'controlador' y le pasamos la tabla 'tblAdmin'
    controlador.cambiarVistaTabla(opcionSeleccionada, tablaPeliculas);
    }//GEN-LAST:event_cmbSeccionAdminActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new VistaAdministrador().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAñadir;
    private javax.swing.JButton btnConfigurarContraseña;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JButton btnVerVentas;
    private javax.swing.JComboBox<String> cmbSeccionAdmin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblLogoAdmin;
    private javax.swing.JLabel lblañ;
    private javax.swing.JLabel lblbo;
    private javax.swing.JLabel lblcon;
    private javax.swing.JLabel lblmo;
    private javax.swing.JLabel lblvi;
    private javax.swing.JTable tablaPeliculas;
    // End of variables declaration//GEN-END:variables
}
